import { useState } from "react";
import { BriefcaseBusiness, CarFront, ChevronRight, Clock3, MapPinned, PackageCheck, Route, UsersRound } from "lucide-react";

const cases = [
  { id: "urban", label: "Taxi urbano", icon: CarFront, title: "Muévete por la ciudad con una ruta clara.", copy: "Solicitud, conductor y seguimiento en un mismo flujo para viajes cotidianos.", points: ["Solicitud en pocos pasos", "Ruta visible", "Seguimiento de viaje"], visualIcon: Route, action: "Explorar viajes" },
  { id: "airport", label: "Aeropuerto", icon: Clock3, title: "Llega con visibilidad sobre tu tiempo de viaje.", copy: "Una experiencia preparada para recorridos con destino, hora y seguimiento importantes.", points: ["Destino estructurado", "Tiempo estimado", "Estado del viaje"], visualIcon: MapPinned, action: "Explorar aeropuerto" },
  { id: "parcel", label: "Paquetes", icon: PackageCheck, title: "Convierte un envío en una experiencia rastreable.", copy: "Solicita una entrega, mantén contexto de recogida y destino, y acompaña el estado de cada etapa.", points: ["Recogida y entrega", "Estado contextual", "Flujo de paquete"], visualIcon: PackageCheck, action: "Explorar paquetes" },
  { id: "business", label: "Flotillas", icon: BriefcaseBusiness, title: "Da visibilidad operativa a toda la flota.", copy: "Una capa de control para equipos que necesitan ver solicitudes, asignación y recorridos desde una misma operación.", points: ["Despacho guiado", "Visión de operación", "Panel por rol"], visualIcon: UsersRound, action: "Explorar flotillas" },
] as const;

export default function UseCaseExplorer() {
  const [selected, setSelected] = useState<typeof cases[number]["id"]>("urban");
  const active = cases.find(item => item.id === selected) || cases[0];
  const VisualIcon = active.visualIcon;
  return <section id="casos-de-uso" className="bg-[#071016] py-20 lg:py-28"><div className="container"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-4 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-emerald-200"><Route size={14} /> Diseñado para cada recorrido</span><h2 className="mt-5 text-3xl font-extrabold leading-tight text-white lg:text-5xl" style={{ fontFamily: "'Sora', sans-serif" }}>Un mismo producto,<br /><span className="text-emerald-300">cuatro contextos claros.</span></h2></div><div className="mt-10 grid gap-5 lg:grid-cols-[.78fr_1.22fr]"><div className="grid grid-cols-2 gap-3 lg:grid-cols-1">{cases.map(item => { const Icon = item.icon; const current = item.id === selected; return <button key={item.id} onClick={() => setSelected(item.id)} className={`rounded-2xl border p-4 text-left transition ${current ? "border-emerald-300/45 bg-emerald-300/10 text-white" : "border-white/10 bg-white/[.035] text-white/55 hover:bg-white/[.06]"}`}><Icon size={19} className={current ? "text-emerald-300" : "text-white/45"} /><p className="mt-3 text-sm font-bold">{item.label}</p></button>; })}</div><div className="relative overflow-hidden rounded-3xl border border-white/12 bg-white/[.045] p-6 lg:p-9"><div className="pointer-events-none absolute right-[-3rem] top-[-3rem] h-48 w-48 rounded-full bg-emerald-300/10 blur-3xl" /><div className="relative grid gap-7 md:grid-cols-[1fr_.7fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-200">{active.label}</p><h3 className="mt-4 text-2xl font-extrabold text-white lg:text-3xl" style={{ fontFamily: "'Sora', sans-serif" }}>{active.title}</h3><p className="mt-4 leading-relaxed text-white/60">{active.copy}</p><div className="mt-6 space-y-3">{active.points.map(point => <p key={point} className="flex items-center gap-2 text-sm text-white/75"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />{point}</p>)}</div><button className="mt-7 inline-flex items-center gap-2 font-bold text-emerald-200 transition hover:translate-x-1">{active.action}<ChevronRight size={17} /></button></div><div className="grid min-h-[13rem] place-items-center rounded-2xl border border-emerald-300/20 bg-gradient-to-br from-emerald-300/[.13] to-white/[.03]"><div className="grid h-24 w-24 place-items-center rounded-[2rem] border border-emerald-300/30 bg-[#071016] text-emerald-200 shadow-xl shadow-emerald-950/25"><VisualIcon size={40} /></div></div></div></div></div></div></section>;
}
